import { motion } from 'framer-motion';
import { X } from 'lucide-react';
import { OnboardingPaso } from './OnboardingPaso';
import { OnboardingProgreso } from './OnboardingProgreso';
import type { OnboardingPasoData } from './useOnboarding';

export function OnboardingModal({ nombre, pasos, porcentaje, onStart, onLater, onClose }: { nombre: string; pasos: OnboardingPasoData[]; porcentaje: number; onStart: (paso: OnboardingPasoData) => void; onLater: () => void; onClose: () => void }) {
  return <div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/65 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><motion.div initial={{ opacity: 0, scale: 0.8, y: 12 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ type: 'spring', stiffness: 260, damping: 22 }} className="max-h-[min(90vh,48rem)] w-full max-w-2xl overflow-y-auto rounded-[2rem] border border-white/70 bg-white p-5 shadow-2xl dark:border-white/10 dark:bg-slate-900 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="mb-2 text-xs font-black uppercase tracking-[0.16em] text-gold">Panel administrativo</p><h2 id="onboarding-title" className="text-2xl font-black tracking-tight text-primary dark:text-white">¡Bienvenido, {nombre}!</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Antes de empezar, completa estos {pasos.length} pasos para activar tu cuenta.</p></div><button type="button" onClick={onClose} className="grid size-9 shrink-0 place-items-center rounded-xl text-slate-400 hover:bg-slate-100 dark:hover:bg-white/10" aria-label="Cerrar introducción"><X size={18} /></button></div><div className="mt-5"><div className="mb-2 flex justify-between text-xs font-bold text-slate-500"><span>Tu progreso</span><span>{porcentaje}%</span></div><OnboardingProgreso porcentaje={porcentaje} /></div><ul className="mt-4 divide-y divide-slate-100 dark:divide-white/10">{pasos.map((paso) => <OnboardingPaso key={paso.id} paso={paso} onAction={onStart} />)}</ul><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={onLater} className="rounded-xl px-4 py-3 text-sm font-bold text-slate-500 hover:bg-slate-100 dark:hover:bg-white/10">Hacerlo más tarde</button><button type="button" onClick={() => onStart(pasos.find((paso) => !paso.completado) ?? pasos[0])} className="rounded-xl bg-primary px-5 py-3 text-sm font-black text-white shadow-lg shadow-primary/20 hover:brightness-110">Empezar ahora</button></div></motion.div></div>;
}
