export interface BibleBook {
  id: string;
  name: string;
  abbrev: string;
  chapters: number;
  testament: 'Antiguo' | 'Nuevo';
}

export const BIBLE_BOOKS: BibleBook[] = [
  // Antiguo Testamento
  { id: 'genesis', name: 'Génesis', abbrev: 'Gn', chapters: 50, testament: 'Antiguo' },
  { id: 'exodo', name: 'Éxodo', abbrev: 'Ex', chapters: 40, testament: 'Antiguo' },
  { id: 'levitico', name: 'Levítico', abbrev: 'Lv', chapters: 27, testament: 'Antiguo' },
  { id: 'numeros', name: 'Números', abbrev: 'Nm', chapters: 36, testament: 'Antiguo' },
  { id: 'deuteronomio', name: 'Deuteronomio', abbrev: 'Dt', chapters: 34, testament: 'Antiguo' },
  { id: 'josue', name: 'Josué', abbrev: 'Jos', chapters: 24, testament: 'Antiguo' },
  { id: 'jueces', name: 'Jueces', abbrev: 'Jue', chapters: 21, testament: 'Antiguo' },
  { id: 'rut', name: 'Rut', abbrev: 'Rut', chapters: 4, testament: 'Antiguo' },
  { id: '1-samuel', name: '1 Samuel', abbrev: '1Sm', chapters: 31, testament: 'Antiguo' },
  { id: '2-samuel', name: '2 Samuel', abbrev: '2Sm', chapters: 24, testament: 'Antiguo' },
  { id: '1-reyes', name: '1 Reyes', abbrev: '1Re', chapters: 22, testament: 'Antiguo' },
  { id: '2-reyes', name: '2 Reyes', abbrev: '2Re', chapters: 25, testament: 'Antiguo' },
  { id: '1-cronicas', name: '1 Crónicas', abbrev: '1Cr', chapters: 29, testament: 'Antiguo' },
  { id: '2-cronicas', name: '2 Crónicas', abbrev: '2Cr', chapters: 36, testament: 'Antiguo' },
  { id: 'esdras', name: 'Esdras', abbrev: 'Esd', chapters: 10, testament: 'Antiguo' },
  { id: 'nehemias', name: 'Nehemías', abbrev: 'Neh', chapters: 13, testament: 'Antiguo' },
  { id: 'ester', name: 'Ester', abbrev: 'Est', chapters: 10, testament: 'Antiguo' },
  { id: 'job', name: 'Job', abbrev: 'Job', chapters: 42, testament: 'Antiguo' },
  { id: 'salmos', name: 'Salmos', abbrev: 'Sal', chapters: 150, testament: 'Antiguo' },
  { id: 'proverbios', name: 'Proverbios', abbrev: 'Pr', chapters: 31, testament: 'Antiguo' },
  { id: 'eclesiastes', name: 'Eclesiastés', abbrev: 'Ec', chapters: 12, testament: 'Antiguo' },
  { id: 'cantares', name: 'Cantares', abbrev: 'Cant', chapters: 8, testament: 'Antiguo' },
  { id: 'isaias', name: 'Isaías', abbrev: 'Is', chapters: 66, testament: 'Antiguo' },
  { id: 'jeremias', name: 'Jeremías', abbrev: 'Jer', chapters: 52, testament: 'Antiguo' },
  { id: 'lamentaciones', name: 'Lamentaciones', abbrev: 'Lam', chapters: 5, testament: 'Antiguo' },
  { id: 'ezequiel', name: 'Ezequiel', abbrev: 'Ez', chapters: 48, testament: 'Antiguo' },
  { id: 'daniel', name: 'Daniel', abbrev: 'Dn', chapters: 12, testament: 'Antiguo' },
  { id: 'oseas', name: 'Oseas', abbrev: 'Os', chapters: 14, testament: 'Antiguo' },
  { id: 'joel', name: 'Joel', abbrev: 'Jl', chapters: 3, testament: 'Antiguo' },
  { id: 'amos', name: 'Amós', abbrev: 'Am', chapters: 9, testament: 'Antiguo' },
  { id: 'abdias', name: 'Abdías', abbrev: 'Abd', chapters: 1, testament: 'Antiguo' },
  { id: 'jonas', name: 'Jonás', abbrev: 'Jon', chapters: 4, testament: 'Antiguo' },
  { id: 'miqueas', name: 'Miqueas', abbrev: 'Miq', chapters: 7, testament: 'Antiguo' },
  { id: 'nahum', name: 'Nahúm', abbrev: 'Nah', chapters: 3, testament: 'Antiguo' },
  { id: 'habacuc', name: 'Habacuc', abbrev: 'Hab', chapters: 3, testament: 'Antiguo' },
  { id: 'sofonias', name: 'Sofonías', abbrev: 'Sof', chapters: 3, testament: 'Antiguo' },
  { id: 'hageo', name: 'Hageo', abbrev: 'Hag', chapters: 2, testament: 'Antiguo' },
  { id: 'zacarias', name: 'Zacarías', abbrev: 'Zac', chapters: 14, testament: 'Antiguo' },
  { id: 'malaquias', name: 'Malaquías', abbrev: 'Mal', chapters: 4, testament: 'Antiguo' },

  // Nuevo Testamento
  { id: 'mateo', name: 'Mateo', abbrev: 'Mt', chapters: 28, testament: 'Nuevo' },
  { id: 'marcos', name: 'Marcos', abbrev: 'Mc', chapters: 16, testament: 'Nuevo' },
  { id: 'lucas', name: 'Lucas', abbrev: 'Lc', chapters: 24, testament: 'Nuevo' },
  { id: 'juan', name: 'Juan', abbrev: 'Jn', chapters: 21, testament: 'Nuevo' },
  { id: 'hechos', name: 'Hechos', abbrev: 'Hch', chapters: 28, testament: 'Nuevo' },
  { id: 'romanos', name: 'Romanos', abbrev: 'Rom', chapters: 16, testament: 'Nuevo' },
  { id: '1-corintios', name: '1 Corintios', abbrev: '1Co', chapters: 16, testament: 'Nuevo' },
  { id: '2-corintios', name: '2 Corintios', abbrev: '2Co', chapters: 13, testament: 'Nuevo' },
  { id: 'galatas', name: 'Gálatas', abbrev: 'Gá', chapters: 6, testament: 'Nuevo' },
  { id: 'efesios', name: 'Efesios', abbrev: 'Ef', chapters: 6, testament: 'Nuevo' },
  { id: 'filipenses', name: 'Filipenses', abbrev: 'Flp', chapters: 4, testament: 'Nuevo' },
  { id: 'colosenses', name: 'Colosenses', abbrev: 'Col', chapters: 4, testament: 'Nuevo' },
  { id: '1-tesalonicenses', name: '1 Tesalonicenses', abbrev: '1Ts', chapters: 5, testament: 'Nuevo' },
  { id: '2-tesalonicenses', name: '2 Tesalonicenses', abbrev: '2Ts', chapters: 3, testament: 'Nuevo' },
  { id: '1-timoteo', name: '1 Timoteo', abbrev: '1Ti', chapters: 6, testament: 'Nuevo' },
  { id: '2-timoteo', name: '2 Timoteo', abbrev: '2Ti', chapters: 4, testament: 'Nuevo' },
  { id: 'tito', name: 'Tito', abbrev: 'Tit', chapters: 3, testament: 'Nuevo' },
  { id: 'filemon', name: 'Filemón', abbrev: 'Flm', chapters: 1, testament: 'Nuevo' },
  { id: 'hebreos', name: 'Hebreos', abbrev: 'Heb', chapters: 13, testament: 'Nuevo' },
  { id: 'santiago', name: 'Santiago', abbrev: 'Stg', chapters: 5, testament: 'Nuevo' },
  { id: '1-pedro', name: '1 Pedro', abbrev: '1Pe', chapters: 5, testament: 'Nuevo' },
  { id: '2-pedro', name: '2 Pedro', abbrev: '2Pe', chapters: 3, testament: 'Nuevo' },
  { id: '1-juan', name: '1 Juan', abbrev: '1Jn', chapters: 5, testament: 'Nuevo' },
  { id: '2-juan', name: '2 Juan', abbrev: '2Jn', chapters: 1, testament: 'Nuevo' },
  { id: '3-juan', name: '3 Juan', abbrev: '3Jn', chapters: 1, testament: 'Nuevo' },
  { id: 'judas', name: 'Judas', abbrev: 'Jud', chapters: 1, testament: 'Nuevo' },
  { id: 'apocalipsis', name: 'Apocalipsis', abbrev: 'Ap', chapters: 22, testament: 'Nuevo' }
];
