import type { LucideIcon } from 'lucide-react';
import {
  BookOpen,
  Calendar,
  Gamepad2,
  Globe,
  GraduationCap,
  Heart,
  Megaphone,
  Music,
  Radio,
  Send,
  ShoppingBag,
  Sparkles,
  Users,
  Video,
} from 'lucide-react';

export interface SiteNavigationItem {
  id: string;
  path: string;
  title: string;
  subtitle?: string;
  category: 'principal' | 'recursos' | 'comunidad' | 'formacion' | 'misiones' | 'institucional';
  keywords: string[];
  icon: LucideIcon;
  badge?: string;
  external?: boolean;
}

export const SITE_NAVIGATION_ITEMS: SiteNavigationItem[] = [
  // Principal
  {
    id: 'nav-home',
    path: '/',
    title: 'Inicio',
    subtitle: 'Portal principal de Iglesia Jerusalén',
    category: 'principal',
    keywords: ['inicio', 'home', 'principal', 'portal', 'iglesia', 'jerusalen', 'bienvenida'],
    icon: Globe,
  },
  {
    id: 'nav-visita',
    path: '/visita',
    title: 'Planifica tu Visita',
    subtitle: 'Información para asistir por primera vez a nuestros cultos',
    category: 'principal',
    keywords: ['visita', 'primera vez', 'llegar', 'bienvenida', 'asistir', 'culto', 'donde queda'],
    icon: Globe,
  },
  {
    id: 'nav-schedules',
    path: '/#schedules',
    title: 'Horarios de Cultos',
    subtitle: 'Días y horarios de servicios presenciales y virtuales',
    category: 'principal',
    keywords: ['horarios', 'cultos', 'reuniones', 'servicios', 'domingos', 'oracion', 'semana'],
    icon: Calendar,
  },
  {
    id: 'nav-live',
    path: '/en-vivo',
    title: 'Culto en Vivo y Streaming',
    subtitle: 'Transmisión directa de los cultos dominicales y especiales',
    category: 'principal',
    keywords: ['en vivo', 'live', 'transmision', 'streaming', 'directo', 'youtube', 'video', 'culto hoy'],
    icon: Video,
    badge: 'EN VIVO',
  },
  {
    id: 'nav-predicas',
    path: '/predicas',
    title: 'Prédicas y Sermones en Video',
    subtitle: 'Mensajes bíblicos, bosquejos y enseñanzas de los pastores',
    category: 'recursos',
    keywords: ['predicas', 'sermones', 'videos', 'mensajes', 'pastor', 'bosquejos', 'ensenanzas', 'estudios'],
    icon: Video,
  },
  {
    id: 'nav-expositores',
    path: '/expositores',
    title: 'Expositores y Pastores',
    subtitle: 'Perfiles de los oradores y maestros de la iglesia',
    category: 'recursos',
    keywords: ['expositores', 'pastores', 'oradores', 'maestros', 'predicadores', 'liderazgo'],
    icon: Users,
  },
  {
    id: 'nav-podcast',
    path: '/podcast',
    title: 'Podcast y Mensajes de Audio',
    subtitle: 'Reflexiones y mensajes para escuchar en cualquier lugar',
    category: 'recursos',
    keywords: ['podcast', 'audio', 'mensajes', 'spotify', 'reflexiones', 'palabra', 'pastor'],
    icon: Radio,
  },
  {
    id: 'nav-alabanzas',
    path: '/recursos/alabanzas',
    title: 'Biblioteca de Alabanzas e Himnos',
    subtitle: 'Letras, acordes, cifrados y recursos de adoración musical',
    category: 'recursos',
    keywords: ['alabanzas', 'himnos', 'canciones', 'acordes', 'cifrados', 'letras', 'musica', 'coro', 'bateria'],
    icon: Music,
  },
  {
    id: 'nav-biblia',
    path: '/recursos/biblia',
    title: 'Lector Bíblico Digital',
    subtitle: 'Lectura completa de las Sagradas Escrituras Reina Valera',
    category: 'recursos',
    keywords: ['biblia', 'lectura', 'capitulos', 'versiculos', 'concordancia', 'palabra de dios', 'reina valera'],
    icon: BookOpen,
  },
  {
    id: 'nav-plan-lectura',
    path: '/plan-lectura',
    title: 'Plan de Lectura Bíblica Anual',
    subtitle: 'Cronograma guiado para leer la Biblia completa en un año',
    category: 'recursos',
    keywords: ['plan de lectura', 'lectura biblica', 'año', 'devocional', 'guia', 'cronograma'],
    icon: BookOpen,
  },
  {
    id: 'nav-juegos',
    path: '/recursos/juegos',
    title: 'Juegos Bíblicos Educativos',
    subtitle: 'Aprende las Escrituras de forma divertida (Biblionario, Ahorcado, etc.)',
    category: 'recursos',
    keywords: ['juegos', 'biblionario', 'trivias', 'ahorcado', 'memorama', 'ninos', 'jovenes', 'educativo'],
    icon: Gamepad2,
  },
  {
    id: 'nav-peticiones',
    path: '/peticiones',
    title: 'Peticiones de Oración',
    subtitle: 'Comparte tu motivo de oración con el equipo pastoral',
    category: 'comunidad',
    keywords: ['peticiones', 'oracion', 'orar', 'intercesion', 'necesidad', 'pedido', 'ayuda espiritual'],
    icon: Send,
  },
  {
    id: 'nav-comunidad',
    path: '/comunidad',
    title: 'Muro de la Comunidad',
    subtitle: 'Testimonios, reflexiones y publicaciones de los congregantes',
    category: 'comunidad',
    keywords: ['comunidad', 'muro', 'testimonios', 'publicaciones', 'hermanos', 'familia de fe'],
    icon: Users,
  },
  {
    id: 'nav-ministerios',
    path: '/ministerios',
    title: 'Ministerios y Departamentos',
    subtitle: 'Conoce los equipos de servicio y liderazgo de la congregación',
    category: 'comunidad',
    keywords: ['ministerios', 'departamentos', 'equipos', 'jovenes', 'damas', 'caballeros', 'escuela dominical', 'liderazgo'],
    icon: Heart,
  },
  {
    id: 'nav-eventos',
    path: '/eventos',
    title: 'Eventos y Calendario',
    subtitle: 'Próximas actividades, campamentos, conferencias y talleres',
    category: 'comunidad',
    keywords: ['eventos', 'calendario', 'actividades', 'campamento', 'conferencia', 'fechas'],
    icon: Calendar,
  },
  {
    id: 'nav-anuncios',
    path: '/anuncios',
    title: 'Anuncios Parroquiales y Circulares',
    subtitle: 'Comunicaciones oficiales y avisos urgentes de la directiva',
    category: 'comunidad',
    keywords: ['anuncios', 'avisos', 'comunicados', 'circulares', 'noticias', 'parroquial'],
    icon: Megaphone,
  },
  {
    id: 'nav-boletin',
    path: '/boletin',
    title: 'Boletín Dominical Digital',
    subtitle: 'Orden del culto, versículos de la semana y avisos destacados',
    category: 'comunidad',
    keywords: ['boletin', 'dominical', 'orden del culto', 'lecturas de la semana', 'programa'],
    icon: BookOpen,
  },
  {
    id: 'nav-agenda',
    path: '/agenda',
    title: 'Agenda Pública de Actividades',
    subtitle: 'Cronograma mensual de actividades y reuniones de grupo',
    category: 'comunidad',
    keywords: ['agenda', 'cronograma', 'mensual', 'calendario general'],
    icon: Calendar,
  },
  {
    id: 'nav-misiones',
    path: '/misiones',
    title: 'Misiones y Campos Blancos',
    subtitle: 'Obras misioneras, alcance evangelístico y apoyo a obreros',
    category: 'misiones',
    keywords: ['misiones', 'campos misioneros', 'alcance', 'evangelismo', 'obras', 'misioneros'],
    icon: Globe,
  },
  {
    id: 'nav-misiones-explorador',
    path: '/misiones/explorador',
    title: 'Explorador Misionero Interactivo',
    subtitle: 'Mapa y estadísticas de las zonas y etnias no alcanzadas',
    category: 'misiones',
    keywords: ['explorador misionero', 'mapa de misiones', 'joshua project', 'etnias', 'geografia misionera'],
    icon: Globe,
  },
  {
    id: 'nav-aula-virtual',
    path: '/aula-virtual',
    title: 'Aula Virtual y Escuela de Formación',
    subtitle: 'Cursos de discipulado, instituto bíblico y capacitación de líderes',
    category: 'formacion',
    keywords: ['aula virtual', 'lms', 'cursos', 'discipulado', 'instituto biblico', 'clases', 'capacitacion'],
    icon: GraduationCap,
    badge: 'LMS',
  },
  {
    id: 'nav-programas',
    path: '/programas',
    title: 'Programas de Estudio',
    subtitle: 'Planes académicos y curriculares de formación cristiana',
    category: 'formacion',
    keywords: ['programas', 'pensum', 'estudio', 'mallas curriculares', 'diplomados'],
    icon: GraduationCap,
  },
  {
    id: 'nav-publicaciones',
    path: '/publicaciones',
    title: 'Publicaciones y Espacios Editoriales',
    subtitle: 'Artículos, blogs ministeriales, devocionales y estudios escritos',
    category: 'recursos',
    keywords: ['publicaciones', 'blog', 'articulos', 'devocionales', 'revistas', 'lecturas'],
    icon: BookOpen,
  },
  {
    id: 'nav-escuela-dominical',
    path: '/escuela-dominical',
    title: 'Escuela Dominical Infantil',
    subtitle: 'Lecciones, actividades y manualidades para niños y maestros',
    category: 'formacion',
    keywords: ['escuela dominical', 'ninos', 'maestras', 'infantil', 'lecciones biblicas para ninos'],
    icon: Heart,
  },
  {
    id: 'nav-donaciones',
    path: '/donaciones',
    title: 'Diezmos, Ofrendas y Donaciones',
    subtitle: 'Información bancaria segura y aportes para la obra del Señor',
    category: 'institucional',
    keywords: ['donaciones', 'diezmos', 'ofrendas', 'sembrar', 'dar', 'transferencias', 'banco', 'aportes'],
    icon: Heart,
  },
  {
    id: 'nav-tienda',
    path: '/tienda',
    title: 'Tienda de la Iglesia',
    subtitle: 'Biblias, literatura cristiana, agendas, camisetas y recuerdos',
    category: 'institucional',
    keywords: ['tienda', 'comprar', 'libros', 'biblias', 'agendas', 'productos', 'souvenirs'],
    icon: ShoppingBag,
  },
  {
    id: 'nav-nosotros',
    path: '/nosotros',
    title: 'Nosotros e Historia',
    subtitle: 'Conoce nuestra doctrina, visión, misión y trayectoria histórica',
    category: 'institucional',
    keywords: ['nosotros', 'doctrina', 'historia', 'que creemos', 'mision', 'vision', 'pastores'],
    icon: BookOpen,
  },
  {
    id: 'nav-contacto',
    path: '/contacto',
    title: 'Contacto y Ubicación',
    subtitle: 'Dirección física en Milagro, teléfonos, correo y atención de oficina',
    category: 'institucional',
    keywords: ['contacto', 'ubicacion', 'direccion', 'mapa', 'milagro', 'telefono', 'whatsapp', 'oficina'],
    icon: Globe,
  },
  {
    id: 'nav-novedades',
    path: '/novedades',
    title: 'Novedades y Actualizaciones (Changelog)',
    subtitle: 'Historial de versiones, notas de lanzamiento y mejoras de la plataforma',
    category: 'institucional',
    keywords: ['novedades', 'changelog', 'actualizaciones', 'versiones', 'cambios', 'mejoras', 'releases'],
    icon: Sparkles,
    badge: 'NUEVO',
  },
  {
    id: 'nav-reservas',
    path: '/reservas',
    title: 'Reserva de Espacios',
    subtitle: 'Solicitud para uso del templo, salones y auditorio',
    category: 'institucional',
    keywords: ['reservas', 'espacios', 'salon', 'auditorio', 'templo', 'solicitud de evento'],
    icon: Calendar,
  },
  {
    id: 'nav-cumpleanos',
    path: '/cumpleanos',
    title: 'Cumpleaños de la Congregación',
    subtitle: 'Felicita a los hermanos que celebran su vida este mes',
    category: 'comunidad',
    keywords: ['cumpleanos', 'aniversarios', 'fechas especiales', 'hermanos'],
    icon: Sparkles,
  },
  {
    id: 'nav-mi-iglesia',
    path: '/mi-iglesia',
    title: 'Mi Iglesia y Credencial Digital',
    subtitle: 'Panel personal del congregante con carnet y registro de membresía',
    category: 'comunidad',
    keywords: ['mi iglesia', 'credencial', 'carnet', 'perfil', 'membresia', 'mi cuenta'],
    icon: Users,
  },
  {
    id: 'nav-voluntariado',
    path: '/mi-horario',
    title: 'Cronograma de Voluntariado y Servidores',
    subtitle: 'Turnos asignados para sonido, ujieres, alabanza y multimedia',
    category: 'comunidad',
    keywords: ['voluntariado', 'servidores', 'turnos', 'horario de servicio', 'ujieres', 'sonido'],
    icon: Calendar,
  },
];
