import { useEffect, useState } from 'react';
import { CalendarDays, Clock3, Loader2, MapPin, Sparkles } from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import { supabase } from '../../config/supabase';

interface PublicAgendaItem { id: string; tipo: string; titulo: string; persona_nombre: string | null; ubicacion: string | null; fecha_inicio: string; fecha_fin: string | null; todo_el_dia: boolean; estado: string; prioridad: string; color: string; fuente: string; }
const dateLabel = (value: string) => new Intl.DateTimeFormat('es-CO', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date(value));

export default function PublicAgenda() {
  const [items, setItems] = useState<PublicAgendaItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const load = async () => { const { data, error: queryError } = await supabase.from('agenda_publica').select('*').gte('fecha_inicio', new Date().toISOString()).order('fecha_inicio').limit(50); if (queryError) setError('No pudimos cargar las actividades públicas.'); else setItems((data ?? []) as PublicAgendaItem[]); setLoading(false); }; void load(); }, []);
  return <><Helmet><title>Agenda pública | Iglesia Jerusalén</title><meta name="description" content="Consulta las próximas actividades públicas de Iglesia Jerusalén." /></Helmet><main className="min-h-screen bg-[#fbfaf8] pb-24 text-slate-950"><section className="bg-[#1e1558] px-5 pb-14 pt-24 text-white sm:px-8"><div className="mx-auto max-w-5xl"><span className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-amber-200"><CalendarDays size={15} /> Agenda pública</span><h1 className="mt-5 max-w-3xl font-serif text-5xl font-bold leading-tight sm:text-7xl">Lo que estamos viviendo juntos.</h1><p className="mt-5 max-w-xl text-base leading-7 text-indigo-200">Actividades que nuestros pastores y líderes han elegido compartir con toda la congregación.</p></div></section><section className="mx-auto max-w-5xl px-5 py-12 sm:px-8">{loading ? <div className="flex justify-center py-24"><Loader2 className="animate-spin text-indigo-800" /></div> : error ? <div role="alert" className="rounded-3xl border border-red-200 bg-red-50 p-8 text-center text-sm text-red-700">{error}</div> : items.length === 0 ? <div className="rounded-3xl border border-dashed border-slate-300 p-14 text-center text-slate-500"><Sparkles className="mx-auto mb-3 text-amber-500" /><p>Aún no hay actividades públicas programadas.</p></div> : <div className="space-y-4">{items.map((item) => <article key={item.id} className="flex gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:gap-6 sm:p-6"><div className="hidden w-28 shrink-0 text-right sm:block"><p className="text-xs font-black uppercase tracking-wider text-indigo-800">{dateLabel(item.fecha_inicio)}</p><p className="mt-2 text-sm font-black text-slate-500">{item.todo_el_dia ? 'Todo el día' : new Date(item.fecha_inicio).toLocaleTimeString('es-CO', { hour: 'numeric', minute: '2-digit' })}</p></div><div className="min-w-0 flex-1 border-l-4 pl-4" style={{ borderColor: item.color || '#1e1558' }}><p className="text-[10px] font-black uppercase tracking-[.16em] text-amber-600">{item.tipo}</p><h2 className="mt-1 text-xl font-black text-slate-900">{item.titulo}</h2><p className="mt-2 text-sm font-semibold text-slate-500 sm:hidden">{dateLabel(item.fecha_inicio)} · {item.todo_el_dia ? 'Todo el día' : new Date(item.fecha_inicio).toLocaleTimeString('es-CO', { hour: 'numeric', minute: '2-digit' })}</p>{item.persona_nombre && <p className="mt-2 text-sm text-slate-600">Con {item.persona_nombre}</p>}{item.ubicacion && <p className="mt-2 flex items-center gap-1 text-sm text-slate-500"><MapPin size={14} />{item.ubicacion}</p>}<p className="mt-3 flex items-center gap-1 text-xs font-bold text-slate-400"><Clock3 size={13} /> Información publicada por el equipo pastoral</p></div></article>)}</div>}</section></main></>;
}
