-- Analítica editorial anónima: solo cuenta lecturas, nunca almacena IP ni datos personales.

CREATE TABLE IF NOT EXISTS public.editorial_document_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id uuid NOT NULL REFERENCES public.editorial_documents(id) ON DELETE CASCADE,
  session_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS editorial_document_views_document_date_idx
  ON public.editorial_document_views (document_id, created_at DESC);

CREATE INDEX IF NOT EXISTS editorial_document_views_session_date_idx
  ON public.editorial_document_views (session_id, created_at DESC);

ALTER TABLE public.editorial_document_views ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.editorial_document_views FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.track_editorial_document_view(p_document_id uuid, p_session_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF p_session_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.editorial_documents document
    JOIN public.editorial_spaces space ON space.id = document.space_id
    WHERE document.id = p_document_id
      AND space.is_published
      AND (document.status = 'published' OR (document.status = 'scheduled' AND document.scheduled_at <= now()))
      AND (document.published_at IS NULL OR document.published_at <= now())
      AND document.visibility IN ('public', 'password')
  ) THEN
    RETURN false;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.editorial_document_views view
    WHERE view.document_id = p_document_id
      AND view.session_id = p_session_id
      AND view.created_at > now() - interval '30 minutes'
  ) THEN
    RETURN false;
  END IF;

  INSERT INTO public.editorial_document_views (document_id, session_id) VALUES (p_document_id, p_session_id);
  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_editorial_document_analytics(p_document_id uuid)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT CASE WHEN private.can_edit_editorial_space(document.space_id) THEN jsonb_build_object(
    'total_views', (SELECT count(*) FROM public.editorial_document_views view WHERE view.document_id = document.id),
    'views_last_30_days', (SELECT count(*) FROM public.editorial_document_views view WHERE view.document_id = document.id AND view.created_at > now() - interval '30 days')
  ) ELSE '{}'::jsonb END
  FROM public.editorial_documents document WHERE document.id = p_document_id;
$$;

REVOKE ALL ON FUNCTION public.track_editorial_document_view(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.track_editorial_document_view(uuid, uuid) TO anon, authenticated;
REVOKE ALL ON FUNCTION public.get_editorial_document_analytics(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_editorial_document_analytics(uuid) TO authenticated;
