import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, Building2, ChevronRight, FileText, Plus, RefreshCw, Search, Sparkles, Users } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '../../config/supabase';
import type { EditorialSpace } from '../../features/editorial/types';

export default function EditorialManager() {
  const [spaces, setSpaces] = useState<EditorialSpace[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const load = useCallback(async () => {
    setLoading(true);
    const { data, error } = await supabase.from('editorial_spaces').select('*').order('created_at', { ascending: false });
    setLoading(false);
    if (error) { console.error('No se cargaron los espacios editoriales.', error); toast.error('No se pudieron cargar las publicaciones. Verifica la migración editorial.'); return; }
    setSpaces((data ?? []) as EditorialSpace[]);
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const visible = useMemo(() => spaces.filter((space) => `${space.name} ${space.description}`.toLowerCase().includes(query.toLowerCase())), [query, spaces]);

  return <div className="space-y-7">
    <section className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#081630] p-7 text-white shadow-2xl sm:p-9"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-amber-300/15 blur-3xl" /><div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><span className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-amber-300"><Sparkles size={15} /> Centro editorial</span><h1 className="mt-3 font-serif text-3xl font-bold sm:text-4xl">Páginas, blogs y comunidades</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Un solo sistema para publicaciones de la iglesia, bitácoras internas de programas y blogs administrados por cada ministerio.</p></div><div className="grid grid-cols-3 gap-2 text-center"><Metric value={spaces.length} label="Espacios" /><Metric value={spaces.filter((item) => item.is_published).length} label="Públicos" /><Metric value={spaces.filter((item) => item.owner_type === 'ministry').length} label="Ministerios" /></div></div></section>
    <section className="rounded-[1.75rem] border border-slate-200 bg-white/70 p-4 shadow-sm backdrop-blur-xl dark:border-white/10 dark:bg-white/5"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-3.5 text-slate-400" size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar espacio, programa o ministerio…" className="h-12 w-full rounded-xl border border-slate-200 bg-white pl-12 pr-4 text-sm dark:border-white/10 dark:bg-slate-950" /></label><button type="button" onClick={() => void load()} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-bold dark:border-white/10"><RefreshCw size={16} /> Actualizar</button></div></section>
    {loading ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((item) => <div key={item} className="h-64 animate-pulse rounded-3xl bg-slate-200 dark:bg-white/5" />)}</div> : visible.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map((space) => <Link key={space.id} to={`/admin/publicaciones/${space.id}`} className="group overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white/80 shadow-sm transition hover:-translate-y-1 hover:shadow-xl dark:border-white/10 dark:bg-white/5"><div className="relative aspect-[16/8] overflow-hidden bg-gradient-to-br from-blue-950 to-indigo-900">{space.cover_image_url && <img src={space.cover_image_url} alt="" className="h-full w-full object-cover opacity-65 transition duration-700 group-hover:scale-105" />}<div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 to-transparent" /><span className="absolute left-4 top-4 inline-flex items-center gap-1 rounded-full border border-white/15 bg-slate-950/50 px-3 py-1.5 text-[10px] font-black uppercase tracking-wider text-white backdrop-blur-xl">{space.owner_type === 'ministry' ? <Building2 size={12} /> : space.owner_type === 'study_program' ? <BookOpen size={12} /> : <FileText size={12} />}{space.owner_type === 'ministry' ? 'Ministerio' : space.owner_type === 'study_program' ? 'Programa' : 'Iglesia'}</span><span className={`absolute right-4 top-4 h-2.5 w-2.5 rounded-full ${space.is_published ? 'bg-emerald-400' : 'bg-slate-400'}`} title={space.is_published ? 'Publicado' : 'Borrador'} /></div><div className="p-5"><h2 className="font-serif text-xl font-bold">{space.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{space.description}</p><span className="mt-5 flex items-center gap-1 text-xs font-black text-blue-700 dark:text-amber-300">Administrar contenido <ChevronRight size={14} /></span></div></Link>)}</div> : <div className="rounded-[2rem] border border-dashed border-slate-300 p-14 text-center dark:border-white/15"><Plus className="mx-auto text-slate-400" /><h2 className="mt-4 font-serif text-2xl font-bold">Todavía no hay espacios</h2><p className="mt-2 text-sm text-slate-500">Los ministerios crean el suyo desde su panel. Los programas pueden vincular una bitácora interna.</p></div>}
    <section className="grid gap-4 md:grid-cols-3"><Feature icon={FileText} title="Páginas y subpáginas" text="Estructura jerárquica, orden y publicación programada." /><Feature icon={Users} title="Varios editores" text="Propietarios, editores, autores y moderadores por espacio." /><Feature icon={BookOpen} title="Contenido por bloques" text="Texto, imágenes, preguntas, encuestas y dinámicas interactivas." /></section>
  </div>;
}

function Metric({ value, label }: { value: number; label: string }) { return <div className="min-w-20 rounded-2xl border border-white/10 bg-white/10 px-3 py-3 backdrop-blur-xl"><strong className="block text-2xl">{value}</strong><span className="text-[9px] font-bold uppercase tracking-wider text-slate-300">{label}</span></div>; }
function Feature({ icon: Icon, title, text }: { icon: typeof FileText; title: string; text: string }) { return <div className="rounded-2xl border border-slate-200 bg-white/60 p-5 dark:border-white/10 dark:bg-white/5"><Icon className="text-blue-700 dark:text-amber-300" /><strong className="mt-4 block text-sm">{title}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>; }
